name = input("Enter your name: ")
print("Hello ", name)
print("Before we begin please some mandatory questions :\n")
silly = input("Enter a Silly word: ")
Number = input("Enter a number: ")
adj1 = input("Enter a adjective: ")
noun1 = input("Enter a noun: ")
adj2 = input("Enter a adjective: ")
relative = input("Enter a Relative: ")
adj3 = input("Enter a adjective: ")
verb = input("Enter a Verb: ")
adj4 = input("Enter a adjective: ")
adj5 = input("Enter a adjective: ")

print("Hello my name is astronaut {}.".format(name))
print("I am on my way to planet {}".format(silly))
print("I will be gone for {} days".format(Number))
print("I am very {} about the trip, but i will miss my {}".format(adj1, noun1))
print("I have heard that the atmosphere there is {}".format(adj2))
print("Luckily my {} packed me a jacket to keep me {}".format(relative, adj3))
print("When I land on the planet i will {} for joy".format(verb))
print("I am {} to walk on another planet".format(adj4))
print("I could not be more {} for this trip".format(adj5))
print("\n\n Thankyou {} for your time !!! see you again in some other program !".format(name))


